import copy,json,sys
from isolation import R
from judge import preservation,verify

def probe():
    verify((R/'receipts'/'frozen-pin.txt').read_text().strip())
    # Trusted fixed-suite reports generated by judge, not candidate-supplied counts.
    reports=json.loads((R/'receipts'/'measurement.json').read_text())
    b=reports['baseline'];c=reports['candidates'][0]['report']; outcomes=[]
    for p in json.loads((R/'frozen'/'malformed.json').read_text()):
        baseline=copy.deepcopy(b);candidate=copy.deepcopy(c)
        target=baseline if p['target']=='baseline' else candidate
        if p['kind']=='replace_report':
            if p['target']=='baseline':baseline=p['value']
            else:candidate=p['value']
        elif p['kind']=='replace_case':target['cases'][0]=p['value']
        elif p['kind']=='delete_field':del target[p['field']]
        else:del target['cases'][0][p['field']]
        try:
            value=preservation(baseline,candidate)
            outcomes.append({'id':p['id'],'returned':value,'matches_expected':type(value) is bool and value is p['expected']})
        except Exception as exc:
            outcomes.append({'id':p['id'],'exception':type(exc).__name__,'matches_expected':False})
    print(json.dumps({'probe_count':len(outcomes),'matching':sum(o['matches_expected'] for o in outcomes),'raised':sum('exception' in o for o in outcomes),'outcomes':outcomes},indent=2))
if __name__=='__main__':probe()
